- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "DevOps with AWS"
    DURATION: 120HRS
    TRAINER: Sivakumar
  tasks:
  - name: print the variables
    vars: # Tasks level variables
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION}}, Traniner is {{ TRAINER }}"

  - name: print the variables1
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION}}, Traniner is {{ TRAINER }}"