- name: create ec2 and r53 records
  connection: local
  hosts: local
  vars: 
    subnet_id: subnet-0d7dcb5a2da33d7c3
    sg_id: sg-041aea187fe9e09b4
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id: }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"